# Generated by Django 3.0.7 on 2020-06-15 03:57

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reddit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('reddit_name', models.CharField(max_length=21)),
                ('status', models.CharField(default='A', max_length=1)),
                ('auto_post', models.BooleanField(default=False)),
                ('listen', models.BooleanField(default=True)),
                ('allow_multiple_replies_in_post', models.BooleanField(default=False)),
                ('max_post_age_days', models.PositiveIntegerField(default=7)),
            ],
        ),
        migrations.AddConstraint(
            model_name='reddit',
            constraint=models.UniqueConstraint(fields=('reddit_name',), name='uq_reddit_reddit_name'),
        ),
    ]
